In [ ]:
import csv
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.svm import SVC
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
import tensorflow as tf
import keras
from sklearn import preprocessing
import joblib




In [ ]:
row_size = 300
w, h = row_size, 4
data = []
labels = []
temp_2d_array = []
iteration = 0
global_row = 0


In [ ]:
with open('/content/project_data_final.csv', 'r') as csvFile:
    # Create a reader object
    csv_reader = csv.reader(csvFile)
    for row in csv_reader:
        if(iteration == 4):
          data.append(temp_2d_array)
          labels.append(int(row[0]))
          temp_2d_array = []
          iteration = 0
          global_row += 1
        else:
          temp = [int(float(item)) for item in row]
          temp_2d_array.append(temp)
          iteration += 1



In [ ]:
print(data[0])
print(labels[0])
print(len(data))
print(len(labels))

[[-56, -40, -15, -19, -27, -36, -21, -3, -8, -35, -44, -27, -14, -17, -37, -45, -30, -20, -33, -49, -50, -41, -20, -27, -53, -58, -56, -41, -27, -42, -61, -44, -33, -24, -28, -44, -45, -28, -10, -17, -30, -23, -5, -4, -28, -43, -41, -23, 0, -12, -41, -43, -26, -28, -41, -50, -63, -46, -21, -17, -30, -40, -31, -20, -20, -33, -44, -46, -25, -16, -47, -62, -55, -37, -32, -44, -51, -53, -41, -32, -39, -52, -57, -41, -23, -25, -39, -43, -25, -9, -19, -30, -28, -20, -4, -2, -29, -40, -28, -10, -8, -42, -51, -36, -25, -20, -37, -51, -41, -28, -22, -32, -43, -40, -26, -20, -37, -58, -57, -33, -22, -43, -52, -40, -20, -12, -18, -29, -33, -13, -1, -12, -33, -46, -29, -20, -28, -36, -45, -42, -29, -29, -48, -62, -50, -36, -34, -44, -58, -50, -39, -42, -61, -71, -64, -56, -42, -43, -42, -32, -21, -11, -18, -43, -35, -19, -25, -42, -52, -51, -42, -20, -17, -40, -42, -24, -21, -30, -48, -60, -49, -27, -25, -53, -59, -47, -31, -21, -29, -46, -55, -27, -8, -26, -37, -31, -11, -1, -20, -41, -43, -28, -

In [ ]:
data = np.array(data)
min_max_scaler = preprocessing.MinMaxScaler()
iter = 0
for element in data:
  element = min_max_scaler.fit_transform(element)
  data[iter] = element
  iter += 1


In [ ]:
print(data[0])

[[0 0 1 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 1 1]]


In [ ]:
data_train, data_test, labels_train, labels_test = train_test_split(data, labels, test_size=0.20, random_state=47)
data_train = np.array(data_train)
labels_train = np.array(labels_train)
data_test = np.array(data_test)
labels_test = np.array(labels_test)

In [ ]:
# Define a sequential model using TensorFlow's Keras API
model = tf.keras.models.Sequential([

    # First layer: Flatten the input (28x28 images) into a 1D vector (28*28 = 784)
    tf.keras.layers.Flatten(),

    # Second layer: Dense (fully connected) layer with 12 units and sigmoid activation function
    tf.keras.layers.Dense(200, activation='relu'),

    # tf.keras.layers.Dropout(0.2),

    # Third layer: Dense layer with 200 units and sigmoid activation function
    tf.keras.layers.Dense(200, activation='relu'),

    # # Dropout layer: Randomly sets 20% of input units to 0 to prevent overfitting
    # tf.keras.layers.Dropout(0.2),

    # Output layer: Dense layer with 10 units (one for each digit class) and softmax activation
    # The softmax activation is used for multi-class classification, as it outputs probabilities for each class
    tf.keras.layers.Dense(5, activation='softmax')
])

# Compile the model with:
# - 'adam' optimizer (adaptive learning rate optimizer)
# - 'sparse_categorical_crossentropy' loss function (used for multi-class classification)
# - 'accuracy' metric to monitor the performance during training
model.compile(optimizer='adam',
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy'])

In [ ]:
print(data_train.shape)
print(data_test[0].shape)
print(data_train[0])
print(data_train[len(data_train)-1])

(2400, 4, 300)
(4, 300)
[[0 0 0 ... 1 0 0]
 [0 0 0 ... 0 1 0]
 [1 0 1 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
[[0 1 1 ... 0 0 0]
 [0 0 0 ... 0 0 1]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [ ]:
history = model.fit(data_train, labels_train, epochs=3, verbose=1, batch_size = 25)

Epoch 1/3
96/96 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.6946 - loss: 0.8264
Epoch 2/3
96/96 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.9404 - loss: 0.2096
Epoch 3/3
96/96 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9811 - loss: 0.0889


In [ ]:
y_pred = model.predict(data_test)
y_pred_argmax = np.argmax(y_pred, axis=1)
print("Accuracy Score        : ",accuracy_score(labels_test, y_pred_argmax))
print("Classification Report : \n", classification_report(labels_test, y_pred_argmax))


19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step
Accuracy Score        :  0.895
Classification Report : 
               precision    recall  f1-score   support

           0       0.88      0.90      0.89       141
           1       0.90      0.72      0.80       120
           2       0.79      0.91      0.84        97
           3       0.96      0.99      0.97       134
           4       0.95      0.96      0.96       108

    accuracy                           0.90       600
   macro avg       0.89      0.89      0.89       600
weighted avg       0.90      0.90      0.89       600



In [ ]:
model.save('/content/model.h5')

In [ ]:
new_model = keras.models.load_model('/content/model.h5')